- name: Deploy to DigitalOcean
  run: |
    set -e  # Exit on any error
    
    # Compress backend files for faster transfer
    tar -czf ../scribd-downloader-backend.tar.gz .
    
    # Upload to server with connection options
    scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        ../scribd-downloader-backend.tar.gz \
        ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_HOST }}:/tmp/
    
    # Deploy commands executed on the remote server
    ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
        ${{ secrets.DIGITALOCEAN_USER }}@${{ secrets.DIGITALOCEAN_HOST }} '
      set -e  # Exit on any error within SSH session
      
      # Create deployment directory
      mkdir -p /tmp/scribd-downloader-backend-deploy
      
      # Extract files
      tar -xzf /tmp/scribd-downloader-backend.tar.gz -C /tmp/scribd-downloader-backend-deploy
      
      # Ensure target directory exists and clear previous deployment
      sudo mkdir -p /var/www/scribd-downloader-backend
      sudo rm -rf /var/www/scribd-downloader-backend/*
      
      # Copy new files
      sudo cp -r /tmp/scribd-downloader-backend-deploy/* /var/www/scribd-downloader-backend/
      
      # Change ownership of the directory to the current user
      sudo chown -R ${{ secrets.DIGITALOCEAN_USER }}:${{ secrets.DIGITALOCEAN_USER }} /var/www/scribd-downloader-backend
      
      # Change to application directory
      cd /var/www/scribd-downloader-backend
      
      # Install production dependencies
      npm ci --omit=dev
      
      # Stop and delete old PM2 process to ensure a clean start
      pm2 delete scribd-downloader-backend-service || true
      
      # Start new application instance
      pm2 start api.js --name scribd-downloader-backend-service
      
      # Save PM2 configuration to survive reboots
      pm2 save
      
      # Verify deployment
      sleep 3
      pm2 status scribd-downloader-backend-service
      
      # Clean up temporary files on the server
      rm -rf /tmp/scribd-downloader-backend-deploy
      rm /tmp/scribd-downloader-backend.tar.gz
      
      echo "Deployment completed successfully!"
    '